/*
PROBLEM:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.

Input Format 
First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.

Output Format 
Print the required answer for each test case.

Constraints 
1 <= T <= 10^5
10 <= N <= 4 * 10^16 

Sample Input
2
10
100

Sample Output
10
44
*/

#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
using namespace std;

int main() {
    int t;
    long long n, first, second, next, sum;
    cin >> t;
    for (int i = 0; i < t; i++){
        cin >> n;
        first = 1;
        second = 1;
        next = 2;
        sum = 0;
        while (next < n){
            sum += next;
            for (int j = 0; j < 3; j++){ //Every third number in the sequence is even.
                first = second;
                second = next;
                next = first + second;
            }
        }
        cout << sum << endl;
    }
    return 0;
}
